---
- name: K8s Token
  debug:
    msg: "k8sMasterToken {{ hostvars['k8s100']['k8sMasterToken'] }}"

- name: Setp bridge forwarding
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    state: present

- name:  Clear Kube
  block:
  - name: kubeadm reset
    command: kubeadm reset -f

  - name: Clear cni network
    command: ip link delete cni0
    ignore_errors: yes

  - name: Clear flannel network
    command: ip link delete flannel.1
    ignore_errors: yes

  - name: Clear CNI
    file:
      state: absent
      path: /etc/cni/net.d
  
  - name: reset iptables
    command:
      cmd: "{{ item }}"
    with_items:
      - iptables -P INPUT ACCEPT
      - iptables -P FORWARD ACCEPT
      - iptables -P OUTPUT ACCEPT
      - iptables-legacy -P INPUT ACCEPT
      - iptables-legacy -P FORWARD ACCEPT
      - iptables-legacy -P OUTPUT ACCEPT
      - iptables -Z
      - iptables -F
      - iptables -t nat -F
      - iptables -t mangle -F
      - iptables -X
      - iptables-legacy -Z
      - iptables-legacy -F
      - iptables-legacy -t nat -F
      - iptables-legacy -t mangle -F
      - iptables-legacy -X

  when: kubeAdmReset

- name: Join cluster
  command: "kubeadm join 192.168.2.100:6443 --token {{ hostvars['k8s100']['k8sMasterToken'] }} --discovery-token-ca-cert-hash sha256:{{ hostvars['k8s100']['k8sMasterCa'] }}"
