- name: Download Docker Ubunbtu apt gpg file
  # https://opensource.com/article/22/9/deprecated-linux-apt-key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker_ubuntu.asc

- name: Add Docker APT repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable"
