
- name: Set Config
  set_fact:
    targetDir: /opt/gateway
    imageName: DietPi_RPi-ARMv7-Bullseye.7z
    tftpDir: /tftpboot

- name: Ensure group "gateway" exists
  group:
    name: gateway
    state: present

- name: add user gateway
  user:
    name: gateway
    shell: /usr/sbin/nologin
    groups: gateway,tftpwrite

- name: Provide gateway with rw access to tftpboot
  file:
    path: "{{ tftpDir }}"
    group: gateway
    mode: '0775'

- name: images
  file:
    path: "{{ targetDir }}/images"
    state: directory
    mode: '0755'

- name: download os image
  get_url:
    url: "https://dietpi.com/downloads/images/{{ imageName }}"
    dest: "{{ targetDir }}/images/{{ imageName }}"

- name: Python venv tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - python3-pip
    - python-setuptools # Needed for ansible to switch to python3
    - virtualenv

- name: Copy Gateway files
  copy:
    src: python
    dest: "{{ targetDir }}"
  notify: Restart Gateway

- name: Install Gateway app
  pip:
    name: "{{ targetDir }}/python"
    virtualenv: "{{ targetDir }}/venv"
    virtualenv_python: python3.7

- name: Gateway Systemd
  copy:
    src: systemd/gateway.service
    dest: /etc/systemd/system/

- name: Make sure gateway service is running
  systemd:
    name: gateway
    enabled: yes
