---
- name: kubeconfig dir
  file:
    state: directory
    path: "/home/{{ k8sAdminUser }}/.kube"

- debug:
    msg: "{{ hostvars }}"

- name: kubeconfig file
  copy:
    dest: "/home/{{ k8sAdminUser }}/.kube/config"
    content: "{{ hostvars['k8s100.k8s']['kubeconfig'] }}"
    owner: "{{ k8sAdminUser }}"
    group: "{{ k8sAdminUser }}"
    mode: '0640'
