- name: Set Config
  set_fact:
    targetDir: /opt/pyfan

- name: pyfan user
  user:
    name: pyfan
    shell: /usr/sbin/nologin
    groups: gpio

- name: Python venv tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - python3-pip
    - python3-dev
    - python-setuptools # Needed for ansible to switch to python3
    - virtualenv
    - build-essential # needed to perform gcc builds or aarch64

- name: Copy Pyfan files
  copy:
    src: pyfan
    dest: "{{ targetDir }}"
  notify: Restart PyFan

- name: Install PyFan app
  pip:
    name: "{{ targetDir }}/pyfan"
    virtualenv: "{{ targetDir }}/venv"
    virtualenv_python: python3.9

- name: PyFan Systemd
  copy:
    src: pyfan/systemd/pyfan.service
    dest: /etc/systemd/system/

- name: Make sure pyfan service is running
  systemd:
    name: pyfan
    enabled: yes
