---

- name: Install hostname packages
  apt:
    name: dbus
    state: present

- name: Start service dbus, if not started
  ansible.builtin.service:
    name: dbus
    state: started

- name: Set name of host
  hostname:
    name: "{{ inventory_hostname }}"
