---
- hosts: gateway
  vars:
    ansible_user: ansible
    ansible_become: yes
    vlan_interface: eth0
    vlan_tag: "3"
    nfs_exports:
      - /nfs/client1 *(rw,sync,no_subtree_check,no_root_squash)
      - /tftpboot *(rw,sync,no_subtree_check,no_root_squash)
    dnshosts:
      dockerreg: 192.168.2.1
      traefik: 192.168.2.240
  roles:
    - clusterctrl
    - pyfan
    - vlan
    - dnsmasq
    - router
    - initrd
    - dietpiclient
    - gatewayserver
    - docker
    - docker-registry
    # - firmware
    - role: k8s-utils
      tags: k8s
