---
- hosts: k8s
  vars: {}
    # kubeAdmReset: True
  roles:
  - k8s-dependencies
  - hostname
- hosts: k8smaster
  vars:
    kubeAdmReset: true
    k8sAdminUser: k8sadmin
  roles:
  - k8s-master
  - k8s-user
- hosts: k8sworker
  vars:
    kubeAdmReset: true
  roles:
  - k8s-worker
- hosts: gateway
  vars:
    ansible_user: ansible
    ansible_become: yes
    k8sAdminUser: k8sadmin

  roles:
  - k8s-utils
  - k8s-user
# - hosts: k8smaster
#   roles:
#   - k8s-flux
  # - k8s-operators
