{
 "title": "Cluster",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Node Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "node_memory_Active_bytes", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Node Load1",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "kubelet_running_pods", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}