
- name: Download Google apt gpg file
  # https://opensource.com/article/22/9/deprecated-linux-apt-key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc

- name: Add Kubernetes APT repository
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /
    # deb http://apt.kubernetes.io/ kubernetes-yakkety main
