---
#examples: https://gist.github.com/carlosedp/1b72b0d80c960e72f10698e2c95f3f1f
#
#
# - debug: var=ansible_facts

- name: Install kubectl
  apt:
    name: "{{ packages }}"
    update_cache: yes
    state: present
  vars:
    packages:
    - kubectl={{ kubernetes_version }}

- name: Helm Dirs
  file:
    path: /opt/helm
    state: directory
    mode: '0755'

- name: Install Helm
  unarchive:
    src: https://get.helm.sh/helm-v3.13.2-linux-arm.tar.gz
    dest: /opt/helm/
    remote_src: yes
    creates: /opt/helm/linux-arm/helm

- name: Symlink Helm
  file:
    state: link
    src: /opt/helm/linux-arm/helm
    dest: /usr/bin/helm

- name: Flux CLI
  shell: >-
    curl -s https://fluxcd.io/install.sh | bash
