#!/bin/busybox sh

/bin/busybox --install -s

mount -t proc none /proc
mount -t sysfs none /sys

echo 0 > /proc/sys/kernel/printk

mknod /dev/null c 1 3
mknod /dev/tty c 5 0
mdev -s

echo "This script just mounts and boots the rootfs, nothing else!"

hostname imager

ifup lo

attempts=5

while [ $attempts -gt 0 ]; do
  if ifup eth0 ; then
        echo "eth0 interface successfully brought up."
        break
    else
        echo "eth0 interface not yet up. Trying again in 5 seconds..."
        sleep 5
        attempts=$((attempts-1))
    fi
done

if [ $attempts -eq 0 ]; then
    echo "Maximum number of attempts reached. Unable to bring up eth0 interface."
    echo "Rebooting in 10 secs ..."
    sleep 10
    reboot -f
fi



echo IP
ip addr

echo FDISK
fdisk -l

echo MOUNT
mount


/download.sh
RESULT=$?
if [ $RESULT -eq 0 ]; then
  echo Successful imaging
else
  fdisk -l
  echo Failed imaging
  sleep 10
fi

echo Rebooting in 5 secs ....
sleep 5
reboot -f

#/bin/busybox sh
