---
#examples: https://gist.github.com/carlosedp/1b72b0d80c960e72f10698e2c95f3f1f
#
#
# - debug: var=ansible_facts


- name: Install Docker
  apt:
    name: "{{ packages }}"
    update_cache: yes
  vars:
    packages:
    - "docker-ce={{docker_version}}"


- name: Create user and add to wheel and docker
  user:
    name: "{{ k8sAdminUser }}"
    groups:
    - wheel
    - docker
    append: yes
    state: present
    createhome: yes

- name: Add ssh keys
  authorized_key:
    user: "{{ k8sAdminUser }}"
    state: present
    key: "{{ lookup('file', '/home/dietpi/.ssh/id_rsa.pub') }}"

- name: Docker Systemd config
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0644'
  register: dockerDaemonFile

- name: Create Docker systemd file
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'
  register: dockerSystemdFile

# Expose docker on a port BUT better to run registry as a container application.
# https://linuxhint.com/setup_own_docker_image_repository/
# https://docs.docker.com/registry/
- name: Override docker systemd
  copy:
    src: files/docker_override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  when: false


- name: Restart Docker Daemon
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  when: dockerDaemonFile.changed or dockerSystemdFile.changed
