
- name: Copy Firmware config
  copy:
    src: files/bootconf.txt
    dest: /etc/default/bootconf.txt

# - name: Configure stable eeprom channel
#   copy:
#     src: files/rpi-eeprom-update
#     dest: /etc/default/rpi-eeprom-update
#   notify: Restart rpi-eeprom-update

- name: Update firmware config
  command: rpi-eeprom-config --apply /etc/default/bootconf.txt
